# Generated by Django 5.0.2 on 2024-03-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
    ]
